using System.Collections.Generic;
using System.Data.SqlClient;
using InventoryManagementSystem.Models;

namespace InventoryManagementSystem.DAL
{
    public static class CategoryRepository
    {
        public static List<Category> GetAll()
        {
            var list = new List<Category>();
            using (var conn = DatabaseHelper.GetConnection())
            {
                conn.Open();
                using (var cmd = new SqlCommand(
                    "SELECT CategoryID, CategoryName FROM Categories ORDER BY CategoryName", conn))
                using (var r = cmd.ExecuteReader())
                    while (r.Read())
                        list.Add(new Category
                        {
                            CategoryID   = r.GetInt32(0),
                            CategoryName = r.GetString(1)
                        });
            }
            return list;
        }

        // Returns the new CategoryID generated by IDENTITY
        public static int Add(string categoryName)
        {
            using (var conn = DatabaseHelper.GetConnection())
            {
                conn.Open();
                using (var cmd = new SqlCommand(
                    "INSERT INTO Categories (CategoryName) VALUES (@n); SELECT SCOPE_IDENTITY();", conn))
                {
                    cmd.Parameters.AddWithValue("@n", categoryName);
                    return System.Convert.ToInt32(cmd.ExecuteScalar());
                }
            }
        }

        public static void Delete(int categoryId)
        {
            using (var conn = DatabaseHelper.GetConnection())
            {
                conn.Open();
                using (var cmd = new SqlCommand(
                    "DELETE FROM Categories WHERE CategoryID = @id", conn))
                {
                    cmd.Parameters.AddWithValue("@id", categoryId);
                    cmd.ExecuteNonQuery();
                }
            }
        }

        public static bool Exists(string categoryName)
        {
            using (var conn = DatabaseHelper.GetConnection())
            {
                conn.Open();
                using (var cmd = new SqlCommand(
                    "SELECT COUNT(1) FROM Categories WHERE CategoryName = @n", conn))
                {
                    cmd.Parameters.AddWithValue("@n", categoryName);
                    return (int)cmd.ExecuteScalar() > 0;
                }
            }
        }

        public static int? GetIdByName(string categoryName)
        {
            using (var conn = DatabaseHelper.GetConnection())
            {
                conn.Open();
                using (var cmd = new SqlCommand(
                    "SELECT CategoryID FROM Categories WHERE CategoryName = @n", conn))
                {
                    cmd.Parameters.AddWithValue("@n", categoryName);
                    var result = cmd.ExecuteScalar();
                    return result == null ? (int?)null : System.Convert.ToInt32(result);
                }
            }
        }
    }
}
